name: competitions
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.2
  flutter_map: ^4.0.0
  geocoding: ^2.0.5
  latlong2: ^0.8.1
  http: ^0.13.5
  connectivity_plus: ^5.0.2
  google_maps_flutter: ^2.2.3
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # <-- Ajout du package launcher icons

# Configuration pour flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"  # <-- Chemin vers ton image de logo personnalisée

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
    - assets/images/icon.png   # (optionnel, juste pour s'assurer que l'image est bien incluse)
